---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
    cooldown:
      default-days: 3
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
    ignore:
      # We currently need to ignore eslint@v9
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
    cooldown:
      default-days: 3
    groups:
      patch-dependencies:
        update-types:
          - "patch"
        patterns:
          - "*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint*"
          - "typescript-eslint"
        update-types:
          - "major"
          - "minor"
