---
name: Cleans all preview pages for gh-pages

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  clean:
    name: Clean
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: 📥 Get gh-pages tar
        run: wget -q https://github.com/db-ux-design-system/theme-builder/tarball/gh-pages

      - name: ➕ Create dist dir
        run: mkdir dist

      - name: 📦 Unpack Tar
        run: tar -zxf gh-pages -C dist --strip-components 1

      - name: 🗑️ Clean all preview pages
        id: cleanup
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          result-encoding: json
          script: |
            const { default: cleanUpPages } = await import('${{ github.workspace }}/scripts/cleanup-gh-pages.js');
            return await cleanUpPages({github, context});

      - name: 🥅 Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
